name: Build CLI

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v7

      - name: Install Poetry Packages
        run: poetry install

      - name: Build Pyinstaller
        run: poetry run pyinstaller --onefile ./src/redownload_cli.py

      - name: Upload Executables
        uses: softprops/action-gh-release@v0.1.14
        with:
          files: |
            dist/redownload_cli
            dist/redownload_cli.app
            dist/redownload_cli.exe