name: Push to Git Mirrors

on:
  push

jobs:
  Mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Setup SSH Key
        uses: webfactory/ssh-agent@v0.5.4
        with:
            ssh-private-key: ${{ secrets.SSH_KEY }}
      
      - name: Add Gitlab Repo as Remote
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub actions"
          git remote add gitlab git@gitlab.com:morpheus636/redownload.git
      
      - name: Push changes to Gitlab
        run: yes | git push gitlab
